config/routes.rb
Rails.application.routes.draw do
  root 'pages#home'
  resources :houses
  get '/user/:id', to: 'users#destroy', as: :user_delete
  devise_for :admins
  devise_for :users
  get '/admin/dashboard', to: "pages#dashboard"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :houses
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/house.rb
class House < ApplicationRecord
  belongs_to :admin
  validates :title, presence: true, length: {minimum: 3, maximum: 50}
  validates :description, presence: true, length: {minimum: 10, maximum: 250}
  validates :price, presence: true, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 999999.99 }
  
  has_rich_text :description
  has_one_attached :image
  has_many_attached :pictures
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  def after_sign_in_path_for(resource)
    # redirect_to admin_dashboard_path if resource.is_a? Admin
    return admin_dashboard_path if resource.is_a? Admin
    houses_path
  end
end

app/controllers/houses_controller.rb
class HousesController < ApplicationController
  before_action :set_house, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, only: %i[show index]
  before_action :authenticate_admin!, only: %i[edit update create destroy]
  # GET /houses or /houses.json
  def index
    @houses = House.order(id: :asc)
  end

  # GET /houses/1 or /houses/1.json
  def show
  end

  # GET /houses/new
  def new
    @house = House.new
  end

  # GET /houses/1/edit
  def edit
  end

  # POST /houses or /houses.json
  def create
    @house = House.new(house_params)

    @house.admin_id = current_admin.id

    respond_to do |format|
      if @house.save
        format.html { redirect_to admin_dashboard_path, notice: "La casa ha sido correctamente creada." }
        format.json { render :show, status: :created, location: @house }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /houses/1 or /houses/1.json
  def update
    respond_to do |format|
      if @house.update(house_params)
        format.html { redirect_to admin_dashboard_path, notice: "La casa ha sido correctamente actualizada." }
        format.json { render :show, status: :ok, location: @house }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @house.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /houses/1 or /houses/1.json
  def destroy
    @house.destroy

    respond_to do |format|
      format.html { redirect_to houses_url, notice: "House was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_house
      @house = House.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def house_params
      params.require(:house).permit(:title, :description, :admin_id, :price, :image, pictures: [])
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_admin!, only: %i[dashboard] 
  def home
  end

  def dashboard
    @users = User.all
    @houses = House.order(id: :asc)
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def destroy
    @user = User.find(params[:id])
    if @user.destroy
      redirect_to admin_dashboard_path, notice: "Usuario #{@user.email} eliminado"
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/houses_helper.rb
module HousesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/houses/_form.html.erb
<%= form_with(model: house) do |form| %>
  <% if house.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

      <ul>
        <% house.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="mb-3">
    <%= form.label :title, "Titulo de la casa", class:"form-label fs-3" %>
    <%= form.text_field :title, class: "form-control", placeholder: "Casa..."%>
  </div>

  <div>
    <%= form.label :description, "Descripcion de la casa", class:"form-label fs-3" %>
    <%= form.rich_text_area :description, class: "form-control dashboard__area "%>
  </div>

  <div>
    <%= form.label :price, "Agrega el precio de la casa", class: "form-label fs-3" %>
    <%= form.number_field :price, step: 0.01, class: "form-control" %>
  </div>

  <div>
    <%= form.label :image, "Agrega una imagen de muestra para la casa", class: "form-label fs-3 my-3" %>
    <%= form.file_field :image, class: "form-control form-control-lg" %>
  </div>

  <div>
    <%= form.label :pictures, "Imagenes de la casa", class: "form-label fs-3 my-3" %>
    <%= form.file_field :pictures, multiple: true, class: "form-control form-control-lg" %>
  </div>


  <%= form.submit 'Crear', class: "btn btn-primary mt-4 w-100" %>
<% end %>

app/views/houses/_house.html.erb
<div class="card text-bg-dark">
  <img src="..." class="card-img" alt="...">
  <%=image_tag(house.image)%>
  <div class="card-img-overlay">
    <h5 class="card-title">Card title</h5>
    <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
    <p class="card-text"><small>Last updated 3 mins ago</small></p>
  </div>
</div>

app/views/houses/edit.html.erb
<h1>Editing house</h1>

<%= render "form", house: @house %>

<br>

<div>
  <%= link_to "Show this house", @house %> |
  <%= link_to "Back to houses", houses_path %>
</div>

app/views/houses/index.html.erb
<section class="section-products">
  <div class="container">
    <div class="row justify-content-center text-center">
      <div class="col-md-8 col-lg-6">
        <div class="header">
          <h2>Casas en Venta</h2>
        </div>
      </div>
    </div>
    <div>
      <% if @houses.length < 0 %>
        <h1>No hay casas disponibles aun...</h1>
      <% else %>
        <% @houses.each do |house| %>
          <%= render house %>
        <% end %>
      <% end %>
    </div>
</section>

app/views/houses/new.html.erb
<h1>New house</h1>

<%= render "form", house: @house %>

<br>

<div>
  <%= link_to "Back to houses", houses_path %>
</div>

app/views/houses/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @house %>

<div>
  <%= link_to "Edit this house", edit_house_path(@house) %> |
  <%= link_to "Back to houses", houses_path %>

  <%= button_to "Destroy this house", @house, method: :delete %>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg|%>
  <div class="alert <%= type == 'notice' ? 'alert-success' : 'alert-warning'%> alert-dismissible fade show" role="alert">
    <strong><%= msg %></strong>
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<div class="container">
  <footer class="d-flex flex-wrap justify-content-between align-items-center py-3 my-4 border-top">
    <p class="col-md-4 mb-0 text-muted">© 2023 Company, Inc</p>
    <%# <a href="/" class="col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none">
      <svg class="bi me-2" width="40" height="32"><use xlink:href="#bootstrap"></use></svg>
    </a> %>
    <%= link_to root_path, class: "col-md-4 d-flex align-items-center justify-content-center mb-3 mb-md-0 me-md-auto link-dark text-decoration-none" do %>
        <%= image_tag('cbc_logo.jpg', size: 50, class: "bi me-2")%>
      <% end %>
    <ul class="nav col-md-4 justify-content-end">
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Fernando Viveros</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">Software Developer Mid Senior</a></li>
      <li class="nav-item"><a href="#" class="nav-link px-2 text-muted">MIMO Software & Design</a></li>
    </ul>
  </footer>
</div>

app/views/layouts/_navbar.html.erb
<%# MOBILE %>
<nav class="navbar navbar-dark bg-dark d-lg-none">
  <div class="container">
    <%= link_to root_path do %>
      <%= image_tag('cbc_logo.jpg', size: 50, class: "img-fluid rounded-circle")%>
    <% end %>
    <button class="navbar-toggler" type="button" data-bs-toggle="offcanvas" data-bs-target="#offcanvasNavbar" aria-controls="offcanvasNavbar">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="offcanvas offcanvas-end text-bg-dark" tabindex="-1" id="offcanvasNavbar" aria-labelledby="offcanvasNavbarLabel">
      <div class="offcanvas-header">
        <h5 class="offcanvas-title" id="offcanvasNavbarLabel">MENU</h5>
        <button type="button" class="btn-close bg-light" data-bs-dismiss="offcanvas" aria-label="Close"></button>
      </div>
        <div class="offcanvas-body">
          <% if !current_user %>  
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item">
                <%= link_to "Inicio", root_path, class: "nav-link #{ 'active' if current_page?(root_path)}"%>
              </li>
              <li class="nav-item">
                <%= link_to "Iniciar Sesion", new_user_session_path, class: "nav-link #{ 'active' if current_page?(new_user_session_path)}"%>
              </li>
              <li class="nav-item">
                <%= link_to "Registrarse", new_user_registration_path, class: "nav-link #{ 'active' if current_page?(new_user_registration_path)}"%>
              </li>
          </ul>
          <% else %>
          <ul class="navbar-nav justify-content-end flex-grow-1 pe-3">
              <li class="nav-item">
                <%= link_to "Inicio", root_path, class: "nav-link #{ 'active' if current_page?(root_path)}"%>
              </li>
              <li class="nav-item">
                <%= link_to 'Ver casas', houses_path, class: "nav-link #{ 'active' if current_page?(houses_path)}"%>
              </li>
              <li class="nav-item">
                <%= link_to "Cerrar Sesion", destroy_user_session_path, class: "nav-link" %>
              </li>
          </ul>
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Buscar">
            <button class="btn btn-outline-success" type="submit">Buscar</button>
          </form>
          <% end %>
        </div>
    </div>
  </div>
</nav>

<%# DESK %>
<nav class="navbar d-none d-lg-block">
  <div class="navbar__content">
    <div class="navbar__content-link">
      <%= link_to root_path do %>
        <%= image_tag('cbc_logo.jpg', size: 50, class: "img-fluid rounded-circle")%>
      <% end %>
    </div>
    <div class="navbar__content-links">
      <%= link_to "Inicio", root_path, class: "nav-link fs-5 link #{ 'active' if current_page?(root_path)}  "%>
      <% if !current_user %>
        <%= link_to "Iniciar Sesión", new_user_session_path, class: "nav-link #{ 'active' if current_page?(new_user_session_path)} fs-5 link"%>
        <%= link_to "Registrarse", new_user_registration_path, class: "nav-link #{ 'active' if current_page?(new_user_registration_path)} fs-5 link"%>
      <% else %>
        <%= link_to 'Ver casas', houses_path, class: "nav-link #{ 'active' if current_page?(houses_path)} fs-5 link"%>
        <%= link_to "Cerrar Sesion", destroy_user_session_path, class: "nav-link link fs-5" %>
        </div>
        <div class="navbar__content-form">
          <form class="d-flex" role="search">
            <input class="form-control me-2" type="search" placeholder="Buscar" aria-label="Buscar">
            <button class="btn btn-outline-success" type="submit">Buscar</button>
          </form>
        </div>
      <% end %>
  </div>
</nav>

app/views/layouts/action_text/contents/_content.html.erb
<div class="trix-content">
  <%= yield -%>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CBC</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= favicon_link_tag asset_path('cbc_logo.jpg') %>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <% unless current_page?(new_admin_session_path) ||  current_page?(admin_dashboard_path)%>
      <%= render 'layouts/navbar' %>
    <% end %>
    <% unless current_page?(admin_dashboard_path) %>
      <%= render 'layouts/flash' %>
    <% end %>
    <%= yield %>
    <%= render 'layouts/footer' %>
    <script src="https://kit.fontawesome.com/8a53de4fd6.js" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pages/_form_edit_house.html.erb
<!-- Modal update house -->
<div class="modal fade" id="exampleModal2" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-xl">
    <div class="modal-content">
      <div class="modal-header">
        <h1 class="modal-title fs-5" id="exampleModalLabel">Actualiza la información de la casa</h1>
      </div>
      <div class="modal-body">
        <%= form_with(model: house) do |form| %>
          <% if house.errors.any? %>
            <div style="color: red">
              <h2><%= pluralize(house.errors.count, "error") %> prohibited this house from being saved:</h2>

              <ul>
                <% house.errors.each do |error| %>
                  <li><%= error.full_message %></li>
                <% end %>
              </ul>
            </div>
          <% end %>

          <div class="mb-3">
            <%= form.label :title, "Titulo de la casa", class:"form-label fs-3" %>
            <%= form.text_field :title, class: "form-control", placeholder: "Casa..."%>
          </div>

          <div>
            <%= form.label :description, "Descripcion de la casa", class:"form-label fs-3" %>
            <%= form.rich_text_area :description, class: "form-control dashboard__area "%>
          </div>

          <div>
            <%= form.label :price, "Agrega el precio de la casa", class: "form-label fs-3" %>
            <%= form.number_field :price, step: 0.01, class: "form-control" %>
          </div>

          <div>
            <%= form.label :image, "Agrega una imagen de muestra para la casa", class: "form-label fs-3 my-3" %>
            <%= form.file_field :image, class: "form-control form-control-lg" %>
          </div>

          <div>
            <%= form.label :pictures, "Imagenes de la casa", class: "form-label fs-3 my-3" %>
            <%= form.file_field :pictures, multiple: true, class: "form-control form-control-lg" %>
          </div>

          <%= form.submit 'Modificar Casa', class: "btn btn-primary mt-4 w-100" %>
        <% end %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
      </div>
    </div>
  </div>
</div>

app/views/pages/_houses_admin.html.erb
<section class="d-none" id="house-section" data-action="click->client#showHouses">
  <div class="d-flex justify-content-between  border-bottom">
    <div
      class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3"
    >
      <h1 class="h2">Registrar las casas</h1>
    </div>
    <div>
      <!-- Button trigger modal -->
      <button type="button" class="btn btn-outline-primary mt-3 mb-3 py-3" data-bs-toggle="modal" data-bs-target="#housesModal">
        Ver Casas Registradas
      </button>
    </div>
  </div>
  <%= render 'houses/form', house: House.new %>
  <!-- Modal -->
  <div class="modal fade" id="housesModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true" data-bs-backdrop="static" data-bs-keyboard="false">
    <div class="modal-dialog modal-dialog-centered modal-lg">
      <div class="modal-content">
        <div class="modal-header">
          <h1 class="modal-title fs-5" id="exampleModalLabel">Casas Registradas</h1>
          <button type="button" class="btn-close" aria-label="Close"></button>
        </div>
        <div class="modal-body">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">#</th>
                <th scope="col">Titulo</th>
                <th scope="col">Fecha de registro</th>
                <th scope="col">Modificar Casa</th>
              </tr>
            </thead>
            <tbody>
              <% houses.each do |house|%>
                <tr>
                  <th scope="row"><%=house.id%></th>
                  <td scope='row'><%= house.title %></td>
                  <td scope='row'><%= house.created_at.strftime('%Y-%m-%d') %></td>
                  <td scope='row'>
                    <button type="button" class="btn btn-primary" id="modal-two" data-dismiss="modal" data-bs-toggle="modal" data-bs-target="#exampleModal2">
                      Modificar
                    </button>
                  </td>
                </tr>
              <% end %>
            </tbody>
          </table>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Cerrar</button>
        </div>
      </div>
    </div>
  </div>
  <% houses.each do |house|%>
    <!-- Modal update house -->
    <%= render 'pages/form_edit_house', house: house %>
  <% end %>
</section>

app/views/pages/_users_admin.html.erb
<section class="d-none" id="user-section">
  <div
    class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
  >
    <h1 class="h2">Usuarios registrados en la página</h1>
  </div>
  
  <table class="table table-hover">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Email</th>
        <th scope="col">Fecha de registro</th>
        <th scope="col">Eliminar usuario</th>
      </tr>
    </thead>
    <tbody>
      <% @users.each do |user|%>
        <tr>
          <th scope="row"><%=user.id%></th>
          <td scope='row'><%= user.email %></td>
          <td scope='row'><%= user.created_at %></td>
          <td scope='row'>
            <%= link_to 'Eliminar', user_delete_path(user), class: "btn btn-warning", method: :delete%>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</section>

app/views/pages/dashboard.html.erb
<header class="navbar navbar-dark sticky-top bg-dark flex-md-nowrap p-0 shadow">
  <%= render 'layouts/flash' %>
  <%= link_to 'CBC ADMIN', admin_dashboard_path, class: "navbar-brand col-md-3 col-lg-2 me-0 px-3"%>
  <button
    class="navbar-toggler position-absolute d-md-none collapsed"
    type="button"
    data-bs-toggle="collapse"
    data-bs-target="#sidebarMenu"
    aria-controls="sidebarMenu"
    aria-expanded="false"
    aria-label="Toggle navigation"
  >
    <span class="navbar-toggler-icon"></span>
  </button>
  <input
    class="form-control form-control-dark w-100"
    type="text"
    placeholder="CONTROLA TU PAGINA"
    aria-label="Buscar"
    disabled
  />
  <div class="navbar-nav">
    <div class="nav-item text-nowrap">
      <%= link_to 'Cerrar sesión', destroy_admin_session_path, class: "nav-link px-3"%>
    </div>
  </div>
</header>
<div class="container-fluid dashboard" data-controller="client">
  <div class="row">
    <nav
      id="sidebarMenu"
      class="col-md-3 col-lg-2 d-md-block bg-light sidebar collapse dashboard__nav"
    >
      <div class="position-sticky pt-3">
        <ul class="nav flex-column gap-5">
          <li class="nav-item">
          <%= link_to admin_dashboard_path, class:"nav-link #{ 'active' if current_page?(admin_dashboard_path)}" do %>
            <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="feather feather-home"
                aria-hidden="true"
              >
                <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"></path>
                <polyline points="9 22 9 12 15 12 15 22"></polyline>
              </svg>
              Dashboard
          <% end %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="feather feather-file"
                aria-hidden="true"
              >
                <path
                  d="M13 2H6a2 2 0 0 0-2 2v16a2 2 0 0 0 2 2h12a2 2 0 0 0 2-2V9z"
                ></path>
                <polyline points="13 2 13 9 20 9"></polyline>
              </svg>
              Citas agendadas
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#" data-action="click->client#createHouses">
              <svg
                xmlns="http://www.w3.org/2000/svg"
                width="24"
                height="24"
                viewBox="0 0 24 24"
                fill="none"
                stroke="currentColor"
                stroke-width="2"
                stroke-linecap="round"
                stroke-linejoin="round"
                class="feather feather-shopping-cart"
                aria-hidden="true"
              >
                <circle cx="9" cy="21" r="1"></circle>
                <circle cx="20" cy="21" r="1"></circle>
                <path
                  d="M1 1h4l2.68 13.39a2 2 0 0 0 2 1.61h9.72a2 2 0 0 0 2-1.61L23 6H6"
                ></path>
              </svg>
              Casas
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#" data-action="click->client#showUsers">
              <svg
                  xmlns="http://www.w3.org/2000/svg"
                  width="24"
                  height="24"
                  viewBox="0 0 24 24"
                  fill="none"
                  stroke="currentColor"
                  stroke-width="2"
                  stroke-linecap="round"
                  stroke-linejoin="round"
                  class="feather feather-users"
                  aria-hidden="true"
                >
                  <path d="M17 21v-2a4 4 0 0 0-4-4H5a4 4 0 0 0-4 4v2"></path>
                  <circle cx="9" cy="7" r="4"></circle>
                  <path d="M23 21v-2a4 4 0 0 0-3-3.87"></path>
                  <path d="M16 3.13a4 4 0 0 1 0 7.75"></path>
                </svg>
              Clientes Registrados
            </a>
          </li>
        </ul>
      </div>
    </nav>
    <main class="col-md-9 ms-sm-auto col-lg-10 px-md-4">
      <section id="home-metrics">
        <div
          class="d-flex justify-content-between flex-wrap flex-md-nowrap align-items-center pt-3 pb-2 mb-3 border-bottom"
        >
          <h1 class="h2">Bienvenido, <%= current_admin.email %></h1>
        </div>
        <div class="container-fluid">
          <h2>Usuarios creados</h2>
        </div>
        <%= line_chart User.group_by_day(:created_at).count %>
        <div class="container-fluid">
          <h2>Casas creadas</h2>
        </div>
        <%= pie_chart House.group_by_day(:created_at).count %>
      </section>
      <%= render 'pages/users_admin' %>
      <%= render 'pages/houses_admin', houses: @houses%>
    </main>
  </div>
</div>